@startuml
skinparam ClassAttributeIconSize 0
package com.qxcode {
  class ComplexNumber {
    - real : double 
    - imaginary : double 
    __
    + ComplexNumber(real : double, imaginary : double)
    + equals(number : ComplexNumber) : boolean
    + toString() : String
    ..
    + getReal() : double
    + getImaginary() : double
    + setReal(real : double)
    + setImaginary(imaginary : double)
    ..
    + sum(number : ComplexNumber) : ComplexNumber
    + subtract(number : ComplexNumber) : ComplexNumber
    + multiply(number : ComplexNumber) : ComplexNumber
    + divide(number : ComplexNumber) : ComplexNumber
  }
}
@enduml